### ISSUE TITLE
Requesting an example on quiz schema in JSON format

### ISSUE THREAD

**Issue by arionrefat** [Devorein/reinforz#2]
In your documentation, in the features section, you said and I quote,
> Each quiz schema can be written in any of one JSON or YAML Format

But in your examples folder quiz examples are only given in YAML format, It would be great if you post some examples in JSON format.

**Comment by Devorein** [comment]
Great idea. Would you be interested in submitting a PR ?

**Comment by arionrefat** [comment]
oh yes, I would love to!
